# Generated by Django 5.2.17 on 2026-08-12 15:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='youtube_video_url',
        ),
        migrations.AddField(
            model_name='property',
            name='social_media_url',
            field=models.URLField(blank=True, help_text='Paste link from Instagram, TikTok, YouTube, Facebook, X (Twitter), or Snapchat.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional. Leave blank if using a social media link.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ref_code',
            field=models.CharField(help_text='e.g. EP-101 or #JJ_001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
