# Generated by Django 5.2.17 on 2026-08-12 17:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_property_youtube_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Chief Executive Officer, Senior Realtor', max_length=150)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField(help_text='Brief professional background description')),
                ('phone', models.CharField(blank=True, help_text='Direct phone line', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.IntegerField(default=0, help_text='Display priority (lowest first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='social_media_url',
            field=models.URLField(blank=True, help_text='Paste link from Instagram, TikTok, YouTube, Facebook, X, or Snapchat.', max_length=500, null=True),
        ),
    ]
