# Generated by Django 5.2.17 on 2026-08-13 17:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember_alter_property_social_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='', help_text='Property primary feature photo (Required)', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='ref_code',
            field=models.CharField(blank=True, help_text='Auto-generated e.g. EP-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='social_media_url',
            field=models.URLField(default='', help_text='Direct link to property post on Instagram, TikTok, YouTube, Facebook, X, etc. (Required)', max_length=500),
            preserve_default=False,
        ),
    ]
